# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_socials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infos',
            new_name='Info',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
    ]
