# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_social_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='inUse',
            field=models.BooleanField(default=False),
        ),
    ]
