# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_social_inuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
