# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20160911_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='inUse',
            new_name='in_use',
        ),
        migrations.AlterField(
            model_name='social',
            name='imageLink',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
