# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20160911_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='timeStamp',
            new_name='time_Stamp',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='imageLink',
            new_name='image_Link',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skillName',
            new_name='skill_Name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='timeStamp',
            new_name='time_Stamp',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='imageLink',
            new_name='image_Link',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='in_use',
            new_name='in_Use',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='timeStamp',
            new_name='time_Stamp',
        ),
    ]
